### ISSUE TITLE
In order to enhance our program as a developer, i can refactor Chirp! to use an external library CLI library

### ISSUE THREAD

**Issue by kilzor33** [ITU-BDSA2024-GROUP25/Chirp#1]

**Comment by kilzor33** [comment]
Acceptance criteria:
   *Arguments passed to the program are not manually parsed.
   *Find a suitable CLI library on nuget.org

**Comment by Cmoos22** [comment]
Partially done - setup done just needs correct values,  instead of printing message parese it to manager
