### ISSUE TITLE
As a Developer, I want to Refactor data persistence to library project SimpleDB, so that we can have more flexibility on later refactoring  

### ISSUE THREAD

**Issue by Cmoos22** [ITU-BDSA2024-GROUP25/Chirp#4]
As a Developer I want to implement our SimpleDB with generic types, so we have no dependencies on specific file types.(increasing modularity)

Acceptance criteria:
  * Ability to store and read cheeps from the database.

**Comment by blade2005** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
